---
- name: project creation
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: create project
      ansible.controller.project:
        name: test
        description: "Foo bar project"
        organization: Default
        state: present
        scm_url: https://github.com/RachnaDodia/rhel.git
